/*
 * MATLAB Compiler: 4.2 (R14SP2)
 * Date: Wed Jun 14 15:42:14 2006
 * Arguments: "-B" "macro_default" "-m" "-W" "main" "-T" "link:exe"
 * "photoPopup" "-d" "T:\vmr7\dhoiem\context\winapp" "-v" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_photoPopup_public_data[] = {'3', '0', '8', '1', '9',
                                                      'D', '3', '0', '0', 'D',
                                                      '0', '6', '0', '9', '2',
                                                      'A', '8', '6', '4', '8',
                                                      '8', '6', 'F', '7', '0',
                                                      'D', '0', '1', '0', '1',
                                                      '0', '1', '0', '5', '0',
                                                      '0', '0', '3', '8', '1',
                                                      '8', 'B', '0', '0', '3',
                                                      '0', '8', '1', '8', '7',
                                                      '0', '2', '8', '1', '8',
                                                      '1', '0', '0', 'C', '4',
                                                      '9', 'C', 'A', 'C', '3',
                                                      '4', 'E', 'D', '1', '3',
                                                      'A', '5', '2', '0', '6',
                                                      '5', '8', 'F', '6', 'F',
                                                      '8', 'E', '0', '1', '3',
                                                      '8', 'C', '4', '3', '1',
                                                      '5', 'B', '4', '3', '1',
                                                      '5', '2', '7', '7', 'E',
                                                      'D', '3', 'F', '7', 'D',
                                                      'A', 'E', '5', '3', '0',
                                                      '9', '9', 'D', 'B', '0',
                                                      '8', 'E', 'E', '5', '8',
                                                      '9', 'F', '8', '0', '4',
                                                      'D', '4', 'B', '9', '8',
                                                      '1', '3', '2', '6', 'A',
                                                      '5', '2', 'C', 'C', 'E',
                                                      '4', '3', '8', '2', 'E',
                                                      '9', 'F', '2', 'B', '4',
                                                      'D', '0', '8', '5', 'E',
                                                      'B', '9', '5', '0', 'C',
                                                      '7', 'A', 'B', '1', '2',
                                                      'E', 'D', 'E', '2', 'D',
                                                      '4', '1', '2', '9', '7',
                                                      '8', '2', '0', 'E', '6',
                                                      '3', '7', '7', 'A', '5',
                                                      'F', 'E', 'B', '5', '6',
                                                      '8', '9', 'D', '4', 'E',
                                                      '6', '0', '3', '2', 'F',
                                                      '6', '0', 'C', '4', '3',
                                                      '0', '7', '4', 'A', '0',
                                                      '4', 'C', '2', '6', 'A',
                                                      'B', '7', '2', 'F', '5',
                                                      '4', 'B', '5', '1', 'B',
                                                      'B', '4', '6', '0', '5',
                                                      '7', '8', '7', '8', '5',
                                                      'B', '1', '9', '9', '0',
                                                      '1', '4', '3', '1', '4',
                                                      'A', '6', '5', 'F', '0',
                                                      '9', '0', 'B', '6', '1',
                                                      'F', 'C', '2', '0', '1',
                                                      '6', '9', '4', '5', '3',
                                                      'B', '5', '8', 'F', 'C',
                                                      '8', 'B', 'A', '4', '3',
                                                      'E', '6', '7', '7', '6',
                                                      'E', 'B', '7', 'E', 'C',
                                                      'D', '3', '1', '7', '8',
                                                      'B', '5', '6', 'A', 'B',
                                                      '0', 'F', 'A', '0', '6',
                                                      'D', 'D', '6', '4', '9',
                                                      '6', '7', 'C', 'B', '1',
                                                      '4', '9', 'E', '5', '0',
                                                      '2', '0', '1', '1', '1'
                                                      , '\0'};

const char *__MCC_photoPopup_name_data = "photoPopup";

const char *__MCC_photoPopup_root_data = "";

const unsigned char __MCC_photoPopup_session_data[] = {'0', '4', 'D', '0',
                                                       '6', '8', '4', '8',
                                                       'F', '1', '9', '4',
                                                       '5', '8', '5', 'F',
                                                       '9', '7', '4', '7',
                                                       'E', '3', '9', '6',
                                                       '6', '7', 'E', '0',
                                                       '2', 'D', 'B', '2',
                                                       '7', 'E', '4', 'F',
                                                       '9', 'D', 'D', 'D',
                                                       '8', 'C', '9', 'A',
                                                       '9', 'E', 'C', 'E',
                                                       '9', 'A', 'A', '8',
                                                       'F', '9', '9', '1',
                                                       '2', 'F', 'D', 'D',
                                                       '6', '0', 'D', '7',
                                                       '3', '1', '3', '3',
                                                       '7', '9', 'D', 'F',
                                                       '0', '8', '5', 'D',
                                                       '2', 'E', '0', '1',
                                                       'A', 'C', '1', '3',
                                                       '4', '3', '1', '2',
                                                       '9', '9', '6', '9',
                                                       '0', 'E', 'A', 'F',
                                                       'C', 'E', '1', '0',
                                                       '9', 'A', '0', 'A',
                                                       'D', 'E', '7', 'E',
                                                       '9', '4', '4', 'A',
                                                       'B', 'E', 'C', '5',
                                                       'F', 'A', '2', '5',
                                                       '1', '5', 'A', '9',
                                                       '9', 'F', 'A', 'E',
                                                       '1', '8', '4', 'B',
                                                       'A', 'B', 'B', '8',
                                                       '0', '3', '8', 'F',
                                                       '3', 'F', '1', '1',
                                                       '6', 'A', '6', 'F',
                                                       'C', '6', '2', '0',
                                                       'E', '3', '5', 'D',
                                                       '7', '3', '0', 'D',
                                                       '6', '7', '1', '7',
                                                       '6', '0', '5', '8',
                                                       'D', '3', '1', 'F',
                                                       'D', '7', '0', 'D',
                                                       'C', '4', '8', '4',
                                                       '1', 'D', 'F', '3',
                                                       '3', '5', '0', '2',
                                                       '0', '9', 'D', '1',
                                                       '9', 'E', 'B', 'C',
                                                       '8', '7', 'C', 'F',
                                                       '0', '3', '5', 'F',
                                                       '7', '2', '9', 'E',
                                                       '1', 'E', 'F', '5',
                                                       'C', 'A', '6', '8',
                                                       '1', '9', '6', 'B',
                                                       '3', '3', 'C', '8',
                                                       'B', 'C', 'A', 'B',
                                                       '1', '5', '8', 'A',
                                                       '0', '2', '9', '9',
                                                       '1', '1', '0', '5',
                                                       '1', 'E', 'C', '8',
                                                       'F', 'C', 'C', 'C',
                                                       '6', '1', '2', 'E',
                                                       'F', 'A', '2', '3'
                                                       , '\0'};

const char *__MCC_photoPopup_matlabpath_data[] = {"photoPopup/",
                                                  "toolbox/compiler/deploy/",
                                                  "geom/", "textons/",
                                                  "tools/drawing/",
                                                  "tools/misc/", "vrml/",
                                                  "$TOOLBOXMATLABDIR/general/",
                                                  "$TOOLBOXMATLABDIR/ops/",
                                                  "$TOOLBOXMATLABDIR/lang/",
                                                  "$TOOLBOXMATLABDIR/elmat/",
                                                  "$TOOLBOXMATLABDIR/elfun/",
                                                  "$TOOLBOXMATLABDIR/specfun/",
                                                  "$TOOLBOXMATLABDIR/matfun/",
                                                  "$TOOLBOXMATLABDIR/datafun/",
                                                  "$TOOLBOXMATLABDIR/polyfun/",
                                                  "$TOOLBOXMATLABDIR/funfun/",
                                                  "$TOOLBOXMATLABDIR/sparfun/",
                                                  "$TOOLBOXMATLABDIR/scribe/",
                                                  "$TOOLBOXMATLABDIR/graph2d/",
                                                  "$TOOLBOXMATLABDIR/graph3d/",
                                                  "$TOOLBOXMATLABDIR/specgraph/",
                                                  "$TOOLBOXMATLABDIR/graphics/",
                                                  "$TOOLBOXMATLABDIR/uitools/",
                                                  "$TOOLBOXMATLABDIR/strfun/",
                                                  "$TOOLBOXMATLABDIR/imagesci/",
                                                  "$TOOLBOXMATLABDIR/iofun/",
                                                  "$TOOLBOXMATLABDIR/audiovideo/",
                                                  "$TOOLBOXMATLABDIR/timefun/",
                                                  "$TOOLBOXMATLABDIR/datatypes/",
                                                  "$TOOLBOXMATLABDIR/verctrl/",
                                                  "$TOOLBOXMATLABDIR/codetools/",
                                                  "$TOOLBOXMATLABDIR/helptools/",
                                                  "$TOOLBOXMATLABDIR/winfun/",
                                                  "$TOOLBOXMATLABDIR/demos/",
                                                  "$TOOLBOXMATLABDIR/timeseries/",
                                                  "$TOOLBOXMATLABDIR/hds/",
                                                  "toolbox/local/",
                                                  "toolbox/compiler/",
                                                  "toolbox/control/control/",
                                                  "toolbox/shared/optimlib/",
                                                  "toolbox/images/images/",
                                                  "toolbox/images/imuitools/",
                                                  "toolbox/images/iptutils/",
                                                  "toolbox/shared/imageslib/",
                                                  "toolbox/optim/",
                                                  "toolbox/stats/"};
const int __MCC_photoPopup_matlabpath_data_count = 47;

const char *__MCC_photoPopup_classpath_data[] = {"java/jar/toolbox/control.jar"};
const int __MCC_photoPopup_classpath_data_count = 1;

const char *__MCC_photoPopup_lib_path_data[] = {"bin/win32/"};
const int __MCC_photoPopup_lib_path_data_count = 1;

const char *__MCC_photoPopup_mcr_application_options[] = { "" };
const int __MCC_photoPopup_mcr_application_option_count = 0;
const char *__MCC_photoPopup_mcr_runtime_options[] = { "" };
const int __MCC_photoPopup_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


